---
detectors:
  Attribute:
    enabled: false
  IrresponsibleModule:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    max_statements: 10
  UtilityFunction:
    enabled: false
