AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'lib/**/**/templates/*'
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 100
Lint/RescueWithoutErrorClass:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
